server:
  port: 8081
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/teachsystem?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开驼峰命名法
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.teachsystem.entity
  mapper-locations: classpath:mapper/*.xml

